ARG PIP_TIMEOUT=30
ARG PIP_INDEX_URL=https://pypi.org/simple
ARG PIP_TRUSTED_HOST

FROM nvidia/cuda:12.1.0-cudnn8-runtime-ubuntu22.04
LABEL maintainer="Michal Lazniewski <mlazniewski@pzh.gov.pl>"

ARG PIP_TIMEOUT
ARG PIP_INDEX_URL
ARG PIP_TRUSTED_HOST

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN apt-get update --fix-missing && apt upgrade -y && \
    apt-get install build-essential pkgconf python3.10 python3-pip default-jre curl unzip wget vim bc htop git gcc zlib1g-dev libbz2-dev libcurl4-gnutls-dev libssl-dev liblzma-dev python3-pycurl screen iqtree mash seqtk -y


RUN pip install ete3 numba numpy==1.23.4 biopython==1.83 psutil pysam 'cgecore>=1.5.5,<2.0' packaging tables==3.8.0 h5py xlrd scikit-learn fiona==1.9.6 geodatasets geopandas plotly
### xlrd - allows to read excels, need that for VFDB
### Not sure why I choose these version of some libraries

WORKDIR /usr/bin
RUN ln -s python3 python

RUN mkdir -p /opt/docker
WORKDIR /opt/docker

RUN wget https://www.drive5.com/downloads/usearch11.0.667_i86linux32.gz ;\
    gunzip usearch11.0.667_i86linux32.gz ;\
    chmod a+x usearch11.0.667_i86linux32


# EToKI

### Szczatkowo, ale ciagle z niego korzystamy
RUN git clone https://github.com/zheminzhou/EToKi.git
WORKDIR /opt/docker/EToKi

### nie sciagamy kraken-a tutaj ale w wersji finalnej bez tego sie nie obejdzie 
### sciaganie bazy kraken-owej opisane jest w /home/michall/kraken2/README_KRAKEN_INSTALL
### tutaj tworzymy tylko katalog i podczas konfigurowania Etoki mowimy mu aby tam zagladal w trakcie pracy
### przy starcie kontenera po prostu mapujemy baze z dysku na kontener przez "-v"
### baza krakenowa wazy 240 Gb  
### usearch must be manually copied to /opt/docker/EToKi/externals,  "--usearch" option seems not to work as expected
### f070664 latest commit as of 02.2026 (repo was not updated since 2024)

RUN git reset --hard f070664; \
    mkdir -p /kraken2_sdb; \
    sed -i "s|https://netcologne.dl.sourceforge.net/project/bbmap/BBMap_38.90.tar.gz|https://sourceforge.net/projects/bbmap/files/BBMap_38.90.tar.gz/download|g" modules/configure.py

    RUN python EToKi.py configure --install --usearch /opt/docker/usearch11.0.667_i86linux32 --link_krakenDB /kraken2_sdb/ --path iqtree=/usr/bin/iqtree2
RUN cp /opt/docker/usearch11.0.667_i86linux32 /opt/docker/EToKi/externals 

ENV PATH="/opt/docker/EToKi:/opt/docker/EToKi/externals/ncbi-blast-2.8.1+/bin:/opt/docker/EToKi/externals/:$PATH"

### Update spades to version 4.2 and link the binary to /opt/docker/EToKi/externals/spades
WORKDIR /opt/docker/
RUN git clone https://github.com/ablab/spades.git ;\
    cd /opt/docker/spades; \
    git reset --hard 874c54b; \
    ./spades_compile.sh -j 10;\
    ln -sfn /opt/docker/spades/bin/spades.py /opt/docker/EToKi/externals/spades.py ;\
    cd /opt/docker

## Updating pilon
RUN wget -O /opt/docker/EToKi/externals/pilon.jar https://github.com/broadinstitute/pilon/releases/download/v1.24/pilon-1.24.jar


# SeqSero2
WORKDIR /opt/docker
RUN git clone https://github.com/denglab/SeqSero2.git; cd /opt/docker/SeqSero2; python3 -m pip install --user . ; cd /opt/docker

# MAFFT
RUN wget https://mafft.cbrc.jp/alignment/software/mafft-7.505-with-extensions-src.tgz ;\
    tar -zxf mafft-7.505-with-extensions-src.tgz; \
    cd /opt/docker/mafft-7.505-with-extensions/core ;\
    make; make install; \
    cd /opt/docker/mafft-7.505-with-extensions/extensions ;\
    make; make install ;\
    cd /opt/docker

RUN git clone https://bitbucket.org/genomicepidemiology/kma.git; cd kma ; make; cd /opt/docker

### Most are just python scripts
ENV VIRULENCEFINDER_VERSION=2.0.5

### Plasmidfinder version is pinned to commit from 	2023-08-16, must be updated eventually
	
RUN git clone https://bitbucket.org/genomicepidemiology/plasmidfinder.git; cd plasmidfinder; git reset --hard 113df12; cd /opt/docker; \
    git clone https://bitbucket.org/genomicepidemiology/speciesfinder.git; cd speciesfinder; python -m pip install --no-cache-dir . ; cd /opt/docker; \
    git clone https://bitbucket.org/genomicepidemiology/spifinder.git; \
    git clone https://bitbucket.org/genomicepidemiology/cgmlstfinder.git; \
    git clone https://bitbucket.org/genomicepidemiology/mlst.git ;\
    pip install resfinder==4.7.0 ;\
    git clone https://bitbucket.org/genomicepidemiology/virulencefinder.git; cd virulencefinder; git checkout tags/${VIRULENCEFINDER_VERSION} ;\
    cd /opt/docker
 
ENV PATH="/opt/docker/kma:$PATH"
#ENV CGE_RESFINDER_RESGENE_DB="/opt/docker/resfinder_db"
#ENV CGE_RESFINDER_RESPOINT_DB="/opt/docker/pointfinder_db"
#ENV CGE_DISINFINDER_DB="/opt/docker/disinfinder_db"

# Metaphlan

### Metaphlan database is downloaded elsewhere /force version 4.2.4/
RUN git clone https://github.com/biobakery/MetaPhlAn.git; \
    cd /opt/docker/MetaPhlAn; \
    git reset --hard b7a434b038df4eb2cac6f04a42669c49fb2344e7; \
    pip install .; \
    cd /opt/docker 

# Prodigal (alternative to Prokka)
RUN git clone https://github.com/hyattpd/Prodigal.git; \
    cd /opt/docker/Prodigal; \
    make install; \
    cd /opt/docker

# Sistr

RUN git clone https://github.com/phac-nml/sistr_cmd; cd /opt/docker/sistr_cmd; python setup.py install; cd /opt/docker
 
## Updating Sistr database
### Sistr only reads database from specific loaction within filesystem amd this cannot be changed

RUN wget https://sairidapublic.blob.core.windows.net/downloads/sistr/database/SISTR_V_1.1_db.tar.gz ;\
    tar -zxvf SISTR_V_1.1_db.tar.gz -C /usr/local/lib/python3.8/dist-packages/sistr ;\
    rm SISTR_V_1.1_db.tar.gz ;\
    touch  /usr/local/lib/python3.8/dist-packages/sistr/dbstatus.txt ;\
    cd /opt/docker


#  NCBI-Blast

### To ensure that this blast is used (not the one installed via EToki) one must explixitly call binaries from /blast/bin/
RUN wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.15.0/ncbi-blast-2.15.0+-x64-linux.tar.gz ;\
    mkdir -p /blast ;\
    tar -zxf ncbi-blast-2.15.0+-x64-linux.tar.gz -C /blast --strip-components=1 ;\
    cd /opt/docker

# Flye

### Do not use make -j, some binaries are not properly created
### Like blast to use this version of Flye (not one from EToki) call /opt/docker/Flye/bin/Flye explicitly
# fix to version 2.8.3-b1695 /commit 886b8c1/
RUN git clone https://github.com/fenderglass/Flye ;\
    cd /opt/docker/Flye ;\
    git reset --hard 886b8c1;\
    make ;\
    cd /opt/docker

# Medaka

RUN pip install urllib3==1.26.16 pysam==0.21.0 parasail==1.3.4 pyabpoa==1.4.0 ;\
    apt update ;\
    apt install python3.10-venv libncurses5-dev -y

# Medaka bacterial pipelien use it, but pipeline should be migrated to use the same image viral pipeline is currently using
# Pin medaka to version 2.0.1

RUN python3 -m pip install --no-cache-dir -U pip wheel "setuptools<81" Cython
RUN apt install -y git-lfs file ;\
    git lfs install ;\ 
    git clone https://github.com/nanoporetech/medaka.git /opt/docker/medaka ;\
    cd /opt/docker/medaka ;\
    git reset --hard 03b5848 ;\
    sed -i 's/pip install pip wheel setuptools --upgrade/pip install -U pip wheel "setuptools<81"/g' Makefile ;\
    sed -i 's/--upgrade pip setuptools/--upgrade pip "setuptools<81"/g' Makefile ;\
    sed -i -E 's/(pip3 install)[[:space:]]+\./\1 --no-build-isolation ./g' Makefile ;\
    sed -i -E 's/(pip install)[[:space:]]+-e[[:space:]]+\./\1 --no-build-isolation -e ./g' Makefile ;\
    sed -i -E 's/(pip install)[[:space:]]+\./\1 --no-build-isolation ./g' Makefile ;\
    make install_root ;\
    cd /opt/docker



# FASTQC

### Pasted from SARS-CoV2 dockerfile

ARG FASTQC_VERSION="0.12.1"
WORKDIR /opt/docker
RUN curl -fsSL "https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v${FASTQC_VERSION}.zip" -o "fastqc_v${FASTQC_VERSION}.zip" && \
    unzip "fastqc_v${FASTQC_VERSION}.zip" && \
    rm "fastqc_v${FASTQC_VERSION}.zip"
ENV PATH="/opt/docker/FastQC:$PATH"

# AMRFIDER

## HAMMER

WORKDIR /opt/docker
RUN cd /opt/docker ;\
    wget http://eddylab.org/software/hmmer/hmmer-3.3.2.tar.gz; tar -zxf hmmer-3.3.2.tar.gz ;\
    cd /opt/docker/hmmer-3.3.2 ;\
    ./configure; make; make install ;\
    cd /opt/docker 
 
## AMRFIDER
RUN git clone https://github.com/ncbi/amr.git ;\
    cd /opt/docker/amr ;\
    git reset --hard 81f509d ;\
    git checkout stxtype ;\
    git submodule update --init ;\
    make; make install ;\
    cd /opt/docker

# ECTyper
# Fixed version 2.0 commit 21f2cbd
RUN git clone https://github.com/phac-nml/ecoli_serotyping.git ;\
    cd /opt/docker/ecoli_serotyping ;\
    git reset --hard 21f2cbd ;\
    pip3 install . ;\
    ectyper_init ;\
    cd /opt/docker

RUN python3 -m pip install --no-cache-dir --force-reinstall --no-deps "biopython==1.83"

# Custom scripts 
COPY bin/bacteria/all_functions_salmonella.py bin/bacteria/run_blastn_ver11.sh bin/bacteria/parse_fastqc_output.py data/bacteria/ne_10m_admin_0_countries.geojson bin/bacteria/plot_historical_data_plotly.py  bin/bacteria/parse_speciesfinder.py /data/

COPY bin/bacteria/json_output_contaminations.py bin/bacteria/coverage_filter.py bin/bacteria/calculate_stats.py bin/bacteria/run_VFDB.sh bin/bacteria/run_fastqc_and_generate_json.py bin/bacteria/initial_mlst_parser.py bin/bacteria/extract_final_stats_parser.py bin/bacteria/resfinder_parser.py bin/bacteria/amrfinder_parser.py bin/bacteria/plasmidfinder_parser.py bin/bacteria/sistr_parser.py bin/bacteria/seqsero_parser.py bin/bacteria/ectyper_parser.py bin/bacteria/spifinder_parser.py bin/bacteria/vfdb_parser.py /bin/bacteria/virulencefinder_parser.py bin/bacteria/prepare_full_json.py /opt/docker/EToKi/externals

COPY VERSION /VERSION

CMD ["/bin/bash"]
